set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
. "\system\environment\.cursor-server\bin\linux-x64\dacbe9b31599a253763e4910eb6ab38704653320/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh"
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
. "\system\environment\.cursor-server\bin\linux-x64\dacbe9b31599a253763e4910eb6ab38704653320/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh"
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
cd /teamspace/studios/this_studio/figures
# First time (or after new checkpoints): export tensors/predictions
python export_figure_data.py
# Generate all 20 figures
python run_all_figures.py --skip-export
ls -la
tar -czvf miccai_results_only.tar.gz *.py *.csv *.log figures/ results/
cat << EOF > .gitignore
# Ignore heavy deep learning model weights
checkpoints/
models/
*.pt
*.pth
*.ckpt

# Ignore heavy raw or processed datasets
*.csv
data/

# Ignore massive training execution logs
*.log

# Ignore IDE settings and python cache
.cursor/
.vscode/
.idea/
__pycache__/
.cache/
.ipynb_checkpoints/
EOF

git init
